name: Email Echo Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: <!--email_off-->21f1000014@ds.study.iitm.ac.in<!--/email_off-->
        run: echo "Hello, world!"
